name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install root dependencies
        run: npm install

      - name: Lint Frontend
        run: npm run lint --workspace=@izzy-crm/frontend

      - name: Build Backend
        run: npm run build --workspace=@izzy-crm/backend

      - name: Build Frontend
        run: npm run build --workspace=@izzy-crm/frontend

      - name: Docker Compose Build
        run: docker compose build
